### ISSUE TITLE
Binder launch issue

### ISSUE THREAD

**Issue by arnim** [okarras/EmpiRE-Analysis#1]
The binder launch [link](https://mybinder.org/v2/gh/okarras/EmpiRE-Analysis/HEAD?labpath=%2Fempire-analysis.ipynb) in the readme currently does not result in a successful build and start.

```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockerk3u67oki'...
HEAD is now at a8d199b Update for re24
Building conda environment for python=3.11
Using PythonBuildPack builder
```

CC @rgaiacs if this is not something systematic let's track that here.

**Comment by rgaiacs** [comment]
The Kubernetes building pod has not extra information:

```
{"message": "Picked Git content provider.\n"}
{"message": "Cloning into '/tmp/repo2dockerde0s0lo8'...\n", "phase": "fetching"}
{"message": "Updating files:  98% (83/84)\r", "phase": "fetching"}
{"message": "Updating files: 100% (84/84)\r", "phase": "fetching"}
{"message": "Updating files: 100% (84/84), done.\n", "phase": "fetching"}
{"message": "HEAD is now at a8d199b Update for re24\n", "phase": "fetching"}
{"message": "Building conda environment for python=3.11\n"}
{"message": "Using PythonBuildPack builder\n", "phase": "building"}
```

**Comment by rgaiacs** [comment]
Dear @okarras,

do you know a good of this repository that you are aware that was working with Binder?

**Comment by rgaiacs** [comment]
Locally, `repo2docker EmpiRE-Analysis` works

```
Picked Local content provider.
Using local repo EmpiRE-Analysis/.
Building conda environment for python=3.11
Using PythonBuildPack builder
Step 1/50 : FROM docker.io/library/buildpack-deps:bionic
...
```

@yuvipanda @minrk any idea why `PythonBuildPack builder` might be failing silent on GESIS cluster?

**Comment by arnim** [comment]
Seems not to be specific to the GESIS cluster
https://binder.curvenote.dev/v2/gh/okarras/EmpiRE-Analysis/HEAD?labpath=%2Fempire-analysis.ipynb

**Comment by arnim** [comment]
`.gitattributes` seems to be the culprit.  Once [.gitattributes](https://github.com/okarras/EmpiRE-Analysis/blob/master/.gitattributes) is [removed](https://github.com/okarras/EmpiRE-Analysis/compare/master...arnim:EmpiRE-Analysis:arnim-patch-2) the build starts just fine.

https://mybinder.org/v2/gh/arnim/EmpiRE-Analysis/arnim-patch-2

@okarras is .gitattributes needed? Can you modify it so that the build passes?

**Comment by okarras** [comment]
> Dear @okarras,
> 
> do you know a good of this repository that you are aware that was working with Binder?

I checked the commit history: https://github.com/okarras/EmpiRE-Analysis/commits/master?before=2eb7478dba09a041e59e97abb5f8b00feaa7fd1d+35

The version before [Starting preparation for RE24 Artifact Track](https://github.com/okarras/EmpiRE-Analysis/commit/8ee54e099d44164e9a8a153b0716d99542586065)  worked on binder. After the 16th of January, I was mainly changing the readme file and other documentation.

**Comment by okarras** [comment]
> Seems not to be specific to the GESIS cluster https://binder.curvenote.dev/v2/gh/okarras/EmpiRE-Analysis/HEAD?labpath=%2Fempire-analysis.ipynb

Yes it is also not working on the mybinder.org page with the same "error".

**Comment by okarras** [comment]
> `.gitattributes` seems to be the culprit. Once [.gitattributes](https://github.com/okarras/EmpiRE-Analysis/blob/master/.gitattributes) is [removed](https://github.com/okarras/EmpiRE-Analysis/compare/master...arnim:EmpiRE-Analysis:arnim-patch-2) the build starts just fine.
> 
> https://mybinder.org/v2/gh/arnim/EmpiRE-Analysis/arnim-patch-2
> 
> @okarras is .gitattributes needed? Can you modify it so that the build passes?

I had to add the gitattributes due to the use of GIT LSF as the folder supplemantary materials contains an RDF dump of the ORKG which is to large for GItHub itself.

I could remove it, but it does not explain why it work 4 weeks ago with the .gitattributes.

i do not really now much about the .gitattributes file, one of our developers help me with  it.

**Comment by rgaiacs** [comment]
`git log -- .gitattributes` returns

```
commit 704b1a3e68b7ff61627f1a36d3d9d704052fdc33
Author: Oliver Karras <oliver.karras@tib.eu>
Date:   Mon Apr 24 13:56:33 2023 +0200

    added rdf dump
```

and `git log 704b1a3e68b7ff61627f1a36d3d9d704052fdc33 -n 2` returns

```
commit 704b1a3e68b7ff61627f1a36d3d9d704052fdc33
Author: Oliver Karras <oliver.karras@tib.eu>
Date:   Mon Apr 24 13:56:33 2023 +0200

    added rdf dump

commit e2178b0669e0e52aa4eb06fe3d8c2eafdbd830df
Author: Oliver Karras <oliver.karras@tib.eu>
Date:   Mon Apr 24 11:07:08 2023 +0200

    added supplementary material
```

I tried both commits and both works:

Before `.gitattributes` was added: https://mybinder.org/v2/gh/okarras/EmpiRE-Analysis/e2178b0669e0e52aa4eb06fe3d8c2eafdbd830df (Work!)

After `.gitattributes` was added: https://mybinder.org/v2/gh/okarras/EmpiRE-Analysis/704b1a3e68b7ff61627f1a36d3d9d704052fdc33 (Also work!)

**Comment by arnim** [comment]
Hi @okarras,

Just tested if [b8631c0](https://github.com/okarras/EmpiRE-Analysis/commit/b8631c0ac4795fbf42e1e41056d8d6426bf48151) (the last commit before [Starting preparation for RE24 Artifact Track](https://github.com/okarras/EmpiRE-Analysis/commit/8ee54e099d44164e9a8a153b0716d99542586065)) works as you said. It seems to have the same issue.

👉 https://mybinder.org/v2/gh/okarras/EmpiRE-Analysis/b8631c0

**Comment by okarras** [comment]
I checked the previous versions. [Test replication on other system](https://github.com/okarras/EmpiRE-Analysis/commit/75608edbdf2e8f5e7369e91fb346184ba369915d) for this version exists a build after it. the error occurs.

**Comment by rgaiacs** [comment]
Dear @okarras,

I don't think that `.gitattributes` is the only culprit, see https://github.com/okarras/EmpiRE-Analysis/issues/1#issuecomment-1954065388, but your recent commit removing `.gitattributes` (https://github.com/okarras/EmpiRE-Analysis/commit/fc11a3e46ac882892f65db757d9b40eea1dfbe08) had a successful build.

If you want to figure out what is the culprit that is working with `.gitattributes` to make the build fail on MyBinder, you can use [Git's bisect](https://git-scm.com/docs/git-bisect).

# Setup

```
$ git bisect start 2eb7478dba09a041e59e97abb5f8b00feaa7fd1d 704b1a3e68b7ff61627f1a36d3d9d704052fdc33
Bisecting: 29 revisions left to test after this (roughly 5 steps)
[b9ef5e873ac69ea7f00b87bf3d46ba6b7cd74b47] Merge branch 'master' of https://github.com/okarras/EmpiRE-Analysis
```

[`2eb7478dba09a041e59e97abb5f8b00feaa7fd1d`](https://github.com/okarras/EmpiRE-Analysis/commit/2eb7478dba09a041e59e97abb5f8b00feaa7fd1d ) is the last commit when the issue was reported and [`704b1a3e68b7ff61627f1a36d3d9d704052fdc33`](https://github.com/okarras/EmpiRE-Analysis/commit/704b1a3e68b7ff61627f1a36d3d9d704052fdc33) is where `.gitattributes` was created.

# Loop

1. Run `git rev-parse HEAD` to obtain the Git commit
2. Visit https://mybinder.org/
   1. fill " GitHub repository name or URL" with https://github.com/okarras/EmpiRE-Analysis/
   2. fill "Git ref (branch, tag, or commit)" with the output of `git rev-parse HEAD`
   3. click on "launch"
3. Wait to see if MyBinder fails during "Using PythonBuildPack builder".
4. Record the result using `git bisect good` or `git bisect bad`

After 5 iterations, you will get a message like

```
123ABC678DEF789 is the first bad commit
commit 123ABC678DEF789
Author:
Date:

    Commit message
```

# Possible first bad commit

Based on https://github.com/okarras/EmpiRE-Analysis/issues/1#issuecomment-1954143742, the first bad commit is 6e411f4c6dc5fdd4386d42072f388e2ec1425cd6.

`git log -3 6e411f4c6dc5fdd4386d42072f388e2ec1425cd6` returns

```
commit 6e411f4c6dc5fdd4386d42072f388e2ec1425cd6
Author: Oliver Karras <oliver.karras@tib.eu>
Date:   Tue Jan 16 15:18:26 2024 +0100

    replication test on second system

commit 75608edbdf2e8f5e7369e91fb346184ba369915d
Author: okarras <me@oliver-karras.de>
Date:   Tue Jan 16 10:46:50 2024 +0100

    Test replication on other system

commit fec29e1bdbffa1b009507e201d42d5ad477ca438
Author: okarras <me@oliver-karras.de>
Date:   Tue Jan 16 10:29:49 2024 +0100

    test on surface
```

https://mybinder.org/v2/gh/okarras/EmpiRE-Analysis/6e411f4c6dc5fdd4386d42072f388e2ec1425cd6 FAILS!

https://mybinder.org/v2/gh/okarras/EmpiRE-Analysis/75608edbdf2e8f5e7369e91fb346184ba369915d works.

# Conclusion

Based on the information on Git commit 6e411f4c6dc5fdd4386d42072f388e2ec1425cd6 , I can**not** tell why MyBinder is failing.

**Comment by okarras** [comment]
Dear @rgaiacs and @arnim 

thank you so much for your help!

I tried a lot in the evening but I cannot really figure out what the problem is. I decided to remove the .gitattributes files and the RDF dump. I will provide it with another solution.

I would never have thought of it without your help. Thank you very much again.

Best
Olli
